format = """
[ ](bg:#C6A0F6)\
$os\
$username\
[](bg:#ED8796 fg:#C6A0F6)\
$directory\
[](fg:#ED8796 bg:#F5A97F )\
$git_branch\
$git_status\
[](fg:#F5A97F bg:#91D7E3)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#91D7E3 bg:#8BD5CA)\
$docker_context\
[](fg:#8BD5CA bg:#B7BDF8)\
$time\
[ ](fg:#B7BDF8)\
\n \
$character\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#C6A0F6 fg:#24273A"
style_root = "bg:#C6A0F6 fg:#24273A"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#C6A0F6 fg:#24273A"
disabled = true                 # Disabled by default

[directory]
style = "bg:#ED8796 fg:#24273A"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#8BD5CA fg:#24273A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#F5A97F fg:#24273A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#F5A97F fg:#24273A"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#91D7E3 fg:#24273A"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "bg:#B7BDF8 fg:#24273A"
format = '[ ♥ $time ]($style)'
